"""drop mitglieder

Revision ID: 107113ae0451
Revises: 8aa7839520d8
Create Date: 2023-03-23 19:14:21.941057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '107113ae0451'
down_revision = '8aa7839520d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitgliederer',
    sa.Column('mitgliederer_id', sa.Integer(), nullable=True),
    sa.Column('mitglied_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mitglied_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['mitgliederer_id'], ['user.id'], )
    )
    op.drop_table('mitglieder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitglieder',
    sa.Column('mitglieder_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mitglied_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mitglied_id'], ['team.id'], name='mitglieder_ibfk_1'),
    sa.ForeignKeyConstraint(['mitglieder_id'], ['user.id'], name='mitglieder_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('mitgliederer')
    # ### end Alembic commands ###
