"""empty message

Revision ID: 3cf4835b9db3
Revises: f4edef275ee5
Create Date: 2023-03-21 18:35:30.072355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf4835b9db3'
down_revision = 'f4edef275ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitglieder',
    sa.Column('mitglieder_id', sa.Integer(), nullable=True),
    sa.Column('mitglied_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mitglied_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['mitglieder_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mitglieder')
    # ### end Alembic commands ###
