"""Tabelle Termin

Revision ID: 623a0a7e2c22
Revises: ac48923bd51b
Create Date: 2023-03-23 08:00:10.460435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623a0a7e2c22'
down_revision = 'ac48923bd51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('termin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminname', sa.String(length=64), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('termin')
    # ### end Alembic commands ###
