"""Beschreibung Termin

Revision ID: 6e3b92525f10
Revises: d07b3e3244ab
Create Date: 2023-03-23 11:19:29.146508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3b92525f10'
down_revision = 'd07b3e3244ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beschreibung', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.drop_column('beschreibung')

    # ### end Alembic commands ###
