"""Neue Attribute Team

Revision ID: a0bf7b2fc5e5
Revises: dbb321499f99
Create Date: 2023-03-23 08:57:14.743903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bf7b2fc5e5'
down_revision = 'dbb321499f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zeit', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.drop_column('zeit')

    # ### end Alembic commands ###
