"""Neue Attribute Team

Revision ID: dbb321499f99
Revises: ff0051d80c2b
Create Date: 2023-03-23 08:54:10.872428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbb321499f99'
down_revision = 'ff0051d80c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.drop_column('zeit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zeit', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
